const players = [
  {
    identifier: 1,
    first_name: "Hector",
    last_name: "Bellerin",
    team: "Arsenal",
    position: "Defender",
    image: "hectorbellerin.jpg",
  },
  {
    identifier: 2,
    first_name: "Petr",
    last_name: "Cech",
    team: "Arsenal",
    position: "Goalkeeper",
    image: "petrcech.jpg",
  },
  {
    identifier: 3,
    first_name: "Olivier",
    last_name: "Giroud",
    team: "Arsenal",
    position: "Striker",
    image: "oliviergiroud.jpg",
  },
  {
    identifier: 4,
    first_name: "Alex",
    last_name: "Iwobi",
    team: "Arsenal",
    position: "Midfielder 2",
    image: "alexiwobi.jpg",
  },
  {
    identifier: 5,
    first_name: "Laurent",
    last_name: "Koscielny",
    team: "Arsenal",
    position: "Defender",
    image: "laurentkoscielny.jpg",
  },
  {
    identifier: 6,
    first_name: "Mesut",
    last_name: "Ozil",
    team: "Arsenal",
    position: "Midfielder 1",
    image: "mesutozil.jpg",
  },
  {
    identifier: 7,
    first_name: "Alexis",
    last_name: "Sanchez",
    team: "Arsenal",
    position: "Striker",
    image: "alexissanchez.jpg",
  },
  {
    identifier: 8,
    first_name: "Theo",
    last_name: "Walcott",
    team: "Arsenal",
    position: "Midfielder 2",
    image: "theowalcott.jpg",
  },
  {
    identifier: 9,
    first_name: "Marcos",
    last_name: "Alonso",
    team: "Chelsea",
    position: "Defender",
    image: "marcosalonso.jpg",
  },
  {
    identifier: 10,
    first_name: "Cesar",
    last_name: "Azpilicueta",
    team: "Chelsea",
    position: "Defender",
    image: "cesarazpilicueta.jpg",
  },
  {
    identifier: 11,
    first_name: "Gary",
    last_name: "Cahill",
    team: "Chelsea",
    position: "Defender",
    image: "garycahill.jpg",
  },
  {
    identifier: 12,
    first_name: "Diego",
    last_name: "Costa",
    team: "Chelsea",
    position: "Striker",
    image: "diegocosta.jpg",
  },
  {
    identifier: 13,
    first_name: "Thibaut",
    last_name: "Courtois",
    team: "Chelsea",
    position: "Goalkeeper",
    image: "thibautcourtois.jpg",
  },
  {
    identifier: 14,
    first_name: "Eden",
    last_name: "Hazard",
    team: "Chelsea",
    position: "Midfielder 1",
    image: "edenhazard.jpg",
  },
  {
    identifier: 15,
    first_name: "Nemanja",
    last_name: "Matic",
    team: "Chelsea",
    position: "Midfielder 2",
    image: "nemanjamatic.jpg",
  },
  {
    identifier: 16,
    first_name: "Victor",
    last_name: "Moses",
    team: "Chelsea",
    position: "Midfielder 2",
    image: "victormoses.jpg",
  },
  {
    identifier: 17,
    last_name: "Willian",
    team: "Chelsea",
    position: "Midfielder 1",
    image: "willian.jpg",
  },
  {
    identifier: 18,
    first_name: "Christian",
    last_name: "Benteke",
    team: "Crystal Palace",
    position: "Striker",
    image: "christianbenteke.jpg",
  },
  {
    identifier: 19,
    first_name: "Daniel",
    last_name: "Amartey",
    team: "Leicester",
    position: "Midfielder 2",
    image: "danielamartey.jpg",
  },
  {
    identifier: 20,
    first_name: "Robert",
    last_name: "Huth",
    team: "Leicester",
    position: "Defender",
    image: "roberthuth.jpg",
  },
  {
    identifier: 21,
    first_name: "Riyad",
    last_name: "Mahrez",
    team: "Leicester",
    position: "Midfielder 2",
    image: "riyadmahrez.jpg",
  },
  {
    identifier: 22,
    first_name: "Wes",
    last_name: "Morgan",
    team: "Leicester",
    position: "Defender",
    image: "wesmorgan.jpg",
  },
  {
    identifier: 23,
    first_name: "Kasper",
    last_name: "Schmeichel",
    team: "Leicester",
    position: "Goalkeeper",
    image: "kasperschmeichel.jpg",
  },
  {
    identifier: 24,
    first_name: "Islam",
    last_name: "Slimani",
    team: "Leicester",
    position: "Striker",
    image: "islamslimani.jpg",
  },
  {
    identifier: 25,
    first_name: "Jamie",
    last_name: "Vardy",
    team: "Leicester",
    position: "Striker",
    image: "jamievardy.jpg",
  },
  {
    identifier: 26,
    first_name: "Sergio",
    last_name: "Aguero",
    team: "Manchester City",
    position: "Striker",
    image: "sergioaguero.jpg",
  },
  {
    identifier: 27,
    first_name: "Claudio",
    last_name: "Bravo",
    team: "Manchester City",
    position: "Goalkeeper",
    image: "claudiobravo.jpg",
  },
  {
    identifier: 28,
    first_name: "Gael",
    last_name: "Clichy",
    team: "Manchester City",
    position: "Defender",
    image: "gaelclichy.jpg",
  },
  {
    identifier: 29,
    first_name: "Kevin",
    last_name: "De Bruyne",
    team: "Manchester City",
    position: "Midfielder 2",
    image: "kevindebruyne.jpg",
  },
  {
    identifier: 30,
    first_name: "Kelechi",
    last_name: "Iheanacho",
    team: "Manchester City",
    position: "Striker",
    image: "kelechiiheanacho.jpg",
  },
  {
    identifier: 31,
    first_name: "Gabriel",
    last_name: "Jesus",
    team: "Manchester City",
    position: "Striker",
    image: "gabrieljesus.jpg",
  },
  {
    identifier: 32,
    first_name: "Aleksandar",
    last_name: "Kolarov",
    team: "Manchester City",
    position: "Defender",
    image: "aleksandarkolarov.jpg",
  },
  {
    identifier: 33,
    first_name: "Leroy",
    last_name: "Sane",
    team: "Manchester City",
    position: "Midfielder 1",
    image: "leroysane.jpg",
  },
  {
    identifier: 34,
    first_name: "David",
    last_name: "Silva",
    team: "Manchester City",
    position: "Midfielder 1",
    image: "davidsilva.jpg",
  },
  {
    identifier: 35,
    first_name: "Raheem",
    last_name: "Sterling",
    team: "Manchester City",
    position: "Midfielder 2",
    image: "raheemsterling.jpg",
  },
  {
    identifier: 36,
    first_name: "Yaya",
    last_name: "Toure",
    team: "Manchester City",
    position: "Midfielder 1",
    image: "yayatoure.jpg",
  },
  {
    identifier: 37,
    first_name: "Eric",
    last_name: "Bailly",
    team: "Manchester United",
    position: "Defender",
    image: "ericbailly.jpg",
  },
  {
    identifier: 38,
    first_name: "David",
    last_name: "De Gea",
    team: "Manchester United",
    position: "Goalkeeper",
    image: "daviddegea.jpg",
  },
  {
    identifier: 39,
    first_name: "Ander",
    last_name: "Herrera",
    team: "Manchester United",
    position: "Midfielder 1",
    image: "anderherrera.jpg",
  },
  {
    identifier: 40,
    first_name: "Zlatan",
    last_name: "Ibrahimovic",
    team: "Manchester United",
    position: "Striker",
    image: "zlatanibrahimovic.jpg",
  },
  {
    identifier: 41,
    first_name: "Phil",
    last_name: "Jones",
    team: "Manchester United",
    position: "Defender",
    image: "philjones.jpg",
  },
  {
    identifier: 42,
    first_name: "Juan",
    last_name: "Mata",
    team: "Manchester United",
    position: "Midfielder 1",
    image: "juanmata.jpg",
  },
  {
    identifier: 43,
    first_name: "Henrikh",
    last_name: "Mkhitaryan",
    team: "Manchester United",
    position: "Midfielder 2",
    image: "henrikhmkhitaryan.jpg",
  },
  {
    identifier: 44,
    first_name: "Paul",
    last_name: "Pogba",
    team: "Manchester United",
    position: "Midfielder 2",
    image: "paulpogba.jpg",
  },
  {
    identifier: 45,
    first_name: "Marcus",
    last_name: "Rashford",
    team: "Manchester United",
    position: "Striker",
    image: "marcusrashford.jpg",
  },
  {
    identifier: 46,
    first_name: "Antonio",
    last_name: "Valencia",
    team: "Manchester United",
    position: "Defender",
    image: "antoniovalencia.jpg",
  },
  {
    identifier: 47,
    first_name: "Joe",
    last_name: "Allen",
    team: "Stoke",
    position: "Midfielder 1",
    image: "joeallen.jpg",
  },
  {
    identifier: 48,
    first_name: "Marko",
    last_name: "Arnautovic",
    team: "Stoke",
    position: "Midfielder 2",
    image: "markoarnautovic.jpg",
  },
  {
    identifier: 49,
    first_name: "Peter",
    last_name: "Crouch",
    team: "Stoke",
    position: "Striker",
    image: "petercrouch.jpg",
  },
  {
    identifier: 50,
    first_name: "Erik",
    last_name: "Pieters",
    team: "Stoke",
    position: "Defender",
    image: "erikpieters.jpg",
  },
  {
    identifier: 51,
    first_name: "Ryan",
    last_name: "Shawcross",
    team: "Stoke",
    position: "Defender",
    image: "ryanshawcross.jpg",
  },
  {
    identifier: 52,
    first_name: "Toby",
    last_name: "Alderweireld",
    team: "Tottenham",
    position: "Defender",
    image: "tobyalderweireld.jpg",
  },
  {
    identifier: 53,
    first_name: "Dele",
    last_name: "Alli",
    team: "Tottenham",
    position: "Midfielder 1",
    image: "delealli.jpg",
  },
  {
    identifier: 54,
    first_name: "Eric",
    last_name: "Dier",
    team: "Tottenham",
    position: "Midfielder 2",
    image: "ericdier.jpg",
  },
  {
    identifier: 55,
    first_name: "Christian",
    last_name: "Eriksen",
    team: "Tottenham",
    position: "Midfielder 2",
    image: "christianeriksen.jpg",
  },
  {
    identifier: 56,
    first_name: "Harry",
    last_name: "Kane",
    team: "Tottenham",
    position: "Striker",
    image: "harrykane.jpg",
  },
  {
    identifier: 57,
    first_name: "Hugo",
    last_name: "Lloris",
    team: "Tottenham",
    position: "Goalkeeper",
    image: "hugolloris.jpg",
  },
  {
    identifier: 58,
    first_name: "Heung-Min",
    last_name: "Son",
    team: "Tottenham",
    position: "Midfielder 1",
    image: "heung-minson.jpg",
  },
  {
    identifier: 59,
    first_name: "Kyle",
    last_name: "Walker",
    team: "Tottenham",
    position: "Defender",
    image: "kylewalker.jpg",
  },
  {
    identifier: 60,
    first_name: "Victor",
    last_name: "Wanyama",
    team: "Tottenham",
    position: "Midfielder 1",
    image: "victorwanyama.jpg",
  },
  {
    identifier: 61,
    first_name: "Nacer",
    last_name: "Chadli",
    team: "West Brom",
    position: "Midfielder 2",
    image: "nacerchadli.jpg",
  },
  {
    identifier: 62,
    first_name: "Jonny",
    last_name: "Evans",
    team: "West Brom",
    position: "Defender",
    image: "jonnyevans.jpg",
  },
  {
    identifier: 63,
    first_name: "Ben",
    last_name: "Foster",
    team: "West Brom",
    position: "Goalkeeper",
    image: "benfoster.jpg",
  },
  {
    identifier: 64,
    first_name: "Gareth",
    last_name: "McAuley",
    team: "West Brom",
    position: "Defender",
    image: "garethmcauley.jpg",
  },
  {
    identifier: 65,
    first_name: "Matt",
    last_name: "Phillips",
    team: "West Brom",
    position: "Midfielder 1",
    image: "mattphillips.jpg",
  },
  {
    identifier: 66,
    first_name: "Salomon",
    last_name: "Rondon",
    team: "West Brom",
    position: "Striker",
    image: "salomonrondon.jpg",
  },
  {
    identifier: 67,
    first_name: "Cristiano",
    last_name: "Ronaldo",
    team: "Al Nassr",
    position: "Striker",
    image: "cristanoronaldo.jpg",
  },
  {
    identifier: 68,
    first_name: "Lionel",
    last_name: "Messi",
    team: "Inter Miami",
    position: "Striker",
    image: "lionelmessi.jpg",
  },
];

export default players;
